In [2]:
import pandas as pd
import numpy as np

# Read the CSV file.
df = pd.read_csv("./S&P 500 2023 Data.csv")

# Categorize states based on the "Change %" column.
def categorize_change(change_percent_str):
    change_percent = float(change_percent_str.replace('%', ''))
    if change_percent > 1:
        return 1  # State 1: Going Up High
    elif 0 <= change_percent <= 1:
        return 2  # State 2: Going Up Low
    elif -1 <= change_percent < 0:
        return 3  # State 3: Going Down Low
    else:
        return 4  # State 4: Going Down High

# Convert "Change %" of each row to state.
df['state'] = df['Change %'].apply(categorize_change)

# Initialize the transition probability matrix.
transition_matrix = np.zeros((4, 4))

# Count state transitions.
for i in range(1, len(df)):
    from_state = df['state'][i - 1] - 1
    to_state = df['state'][i] - 1
    transition_matrix[from_state][to_state] += 1

# Convert to transition probability matrix.
transition_matrix = transition_matrix / transition_matrix.sum(axis=1, keepdims=True)

print("Transition Matrix:")
print(transition_matrix)


Transition Matrix:
[[0.11111111 0.33333333 0.47222222 0.08333333]
 [0.16666667 0.39215686 0.3627451  0.07843137]
 [0.12048193 0.43373494 0.26506024 0.18072289]
 [0.17857143 0.5        0.25       0.07142857]]
